### ISSUE TITLE
OutOfMemoryError in TimeOutListener.java

### ISSUE THREAD

**Issue by alokvnair** [zoho/salesiq-mobilisten-android-sample#11]
Getting large number of OutOfMemoryError in TimeOutListener.java after upgrading to 2.3. Please look into this issue. Thanks!

```

TimeOutListener.java line 85
com.zoho.livechat.android.messaging.wms.common.TimeOutListener.run

Fatal Exception: java.lang.OutOfMemoryError
OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available

```

**Comment by alokvnair** [comment]
Sure @Angu-G Will try to fetch more detail on this and share here.

**Comment by Angu-G** [comment]
Hello @alokvnair, We are closing this issue now since there is no logs trace provided for debugging. As we already mentioned, please check for the application's memory limit. You can reopen this issue anytime if you find any logs trace or any other findings. Thank you.
