### ISSUE TITLE
Attachment icon first tap issue

### ISSUE THREAD

**Issue by alokvnair** [zoho/salesiq-mobilisten-android-sample#15]
Can't start the chat conversation with an image, the file attachment button seems to be non-functioning on tap if no message has been sent yet on the conversation. It works after the first text is sent and the dialog comes up to take action. Is this an intended behaviour or a bug in the SDK? Is there anything we need to pass to SDK to enable this, didn't find anything in documentation related to this. Thanks.

**SDK version** - `2.3.1`

![Screenshot_20201023-143402](https://user-images.githubusercontent.com/8415897/96988056-78486500-1541-11eb-915f-0b25107221d0.jpg)

**Comment by Angu-G** [comment]
Hello @alokvnair, this is intended behavior. Attachment icon will be enabled only after a first message(question).

**Comment by alokvnair** [comment]
Thanks @Angu-G Closing the ticket.
