### ISSUE TITLE
Is there a way to deactivate widget in non business hours?

### ISSUE THREAD

**Issue by manuls** [zoho/salesiq-mobilisten-android-sample#16]
Despite we have configured business hours in the company, the Android widget is always active. Is there any way to configure this?

**Comment by Angu-G** [comment]
Hello @manuls, We do follow business hours config in SDK. But if the Zobot is configured with the option of **24/7 - Round the clock** as the working hours to the website for which SDK is configured, chat widget will be shown in the Android SDK even though the **Hide Chat Widget outside Business Hours** config is enabled in Company settings. This is our current flow. Alternatively, if you choose **During standard business hours** as a working hours option for Zobot, the chat widget will be hidden (Attached screenshot for reference). Also, we are planning to obey only the business hours config irrespective of Zobot in our next update. 


![image](https://user-images.githubusercontent.com/58692424/99561577-1d454900-29ed-11eb-8982-38d4caf0f6fd.png)

If you are facing this issue even though Zobot is not used and **Hide Chat Widget outside Business Hours** config is enabled, you can share your portal details to debug on our end.

**Comment by manuls** [comment]
Hello @Angu-G, thanks for your response

The thing is we dont have Zobot enabled in our SalesIQ configuration, only the chat is avaliable with its configuration hours. Do we have to configure a Zobot to make the widget obey the business hours? 
We would like a behauviour like the web widget: when we are out of the business hours, the widget only lets the customer to leave a message and not chat with us.

**Comment by Angu-G** [comment]
@manuls, You can enable the **Hide Chat Widget outside Business Hours** under the Company settings (Settings -> Company) to hide the chat widget outside business hours.
Behaviour like web widget is not currently available in SDK.

**Comment by Angu-G** [comment]
Hai @manuls, hope your requirement is addressed. We are closing this issue here.
