### ISSUE TITLE
Change background color of the toolbar in Forms view

### ISSUE THREAD

**Issue by manuls** [zoho/salesiq-mobilisten-android-sample#17]
In the documentation there is no item name refered https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization-forms.html 

And there is no name in the SDK to change the color of the toolbar in that view, it is always blue

**Comment by Angu-G** [comment]
Hello @manuls, You can use **colorPrimary** attribute to change the toolbar color of the Form view. We will have this documented separately under the Forms category.

Example:
`<item name="colorPrimary">--custom color--</item>`

**Comment by manuls** [comment]
Roger that. But I find strange that it cannot be changed separately like the other toolbars

**Comment by Angu-G** [comment]
@manuls, We will be having this as a separate attribute like other views in our next update. We will keep you posted here once it is live.

**Comment by Angu-G** [comment]
Hai @manuls, As we committed earlier, a separate attribute for Forms toolbar color is supported in our latest release [2.3.2](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/2.3.2)
Attribute name - **siq_forms_toolbar_backgroundcolor**
Reference - [Doc link](https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization-forms.html)
