### ISSUE TITLE
Cannot translate Submit button in Forms view

### ISSUE THREAD

**Issue by manuls** [zoho/salesiq-mobilisten-android-sample#18]
There is no documentation: https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization-forms.html 

What is the string name to translate that text Button?

**Comment by Angu-G** [comment]
Sorry @manuls, We currently don't have an option to customize the Submit button text. It will be available in our next update.

**Comment by Angu-G** [comment]
Hello @manuls, you can customize the Submit button text in our latest update [2.3.2](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/2.3.2)
Attribute name - **livechat.prechatform.submit**
Reference - [Doc link](https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization-strings.html)
