### ISSUE TITLE
Change background color of statusbar in forms view

### ISSUE THREAD

**Issue by manuls** [zoho/salesiq-mobilisten-android-sample#19]
There is no style related in the documentation, neither the code

**Comment by Angu-G** [comment]
@manuls, We don't have support for this currently. We will have this change in our next update.

**Comment by Angu-G** [comment]
Hello @manuls, We have supported this request in our latest version [v3.0](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/3.0). You can try it out with the following attribute name.
Example:
`<item name="siq_forms_statusbar_color">?attr/colorPrimaryDark</item>`

[Help Doc link](https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization-forms.html)

**Comment by Angu-G** [comment]
@manuls Closing this issue. Thank you!
