### ISSUE TITLE
Not able to send msg (send button greyed out)

### ISSUE THREAD

**Issue by dodeja27** [zoho/salesiq-mobilisten-android-sample#20]
The sending button is always disabled and the first msg is stuck on sending.
Also, the conversations page always shows "awaiting your details" and it keeps loading.
Please see the below Attached screenshots for details. 

![Screenshot_1606997364](https://user-images.githubusercontent.com/53833179/101017382-0592c680-3590-11eb-8001-3e64a00d90f8.png)
![Screenshot_1606997369](https://user-images.githubusercontent.com/53833179/101017398-07f52080-3590-11eb-8143-ff448e96b1f6.png)
![Screenshot_1606997397](https://user-images.githubusercontent.com/53833179/101017400-09264d80-3590-11eb-974c-7e7517eebaa4.png)

**Comment by dodeja27** [comment]
Also sending the visitor's info before starting the chat but keeps getting same result.

![Screenshot_1606999151](https://user-images.githubusercontent.com/53833179/101019275-bd28d800-3592-11eb-941e-87d6be51e8c2.png)

**Comment by Angu-G** [comment]
@dodeja27, can you please share us your portal name?

**Comment by Angu-G** [comment]
Hello @dodeja27, We have sent you a mail last week with detailed information about the cause of this issue. Please check and revert back. Thank you!!
