### ISSUE TITLE
 Connect to maven.zohodl.com:443 [maven.zohodl.com/204.141.42.60] failed: connect timed out

### ISSUE THREAD

**Issue by mohamed0017** [zoho/salesiq-mobilisten-android-sample#21]
> Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.31.
         > Could not get resource 'https://maven.zohodl.com/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.pom'.
            > Could not HEAD 'https://maven.zohodl.com/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.pom'.
               > Connect to maven.zohodl.com:443 [maven.zohodl.com/204.141.42.60] failed: connect timed out

**Comment by Angu-G** [comment]
Hello @mohamed0017,  Can you please mention the Mobilisten version and the Kotlin version.

**Comment by mohamed0017** [comment]
Mobilisten version : com.zoho.salesiq:mobilisten:2.0
kotlin_version = '1.4.10'

**Comment by Angu-G** [comment]
Thank you @mohamed0017! We will check this issue. In the meantime can you please update to our latest version (2.3.2) and see whether the issue persists.

**Comment by mohamed0017** [comment]
I update it to latest version (2.3.2) but the issue still exists

**Comment by Angu-G** [comment]
Hai @mohamed0017, Can you please check now?

**Comment by mohamed0017** [comment]
Hi @Angu-G It's working fine now, Thanks
