### ISSUE TITLE
Zoho MobiListen not intializing. Error code 1000

### ISSUE THREAD

**Issue by alokvnair** [zoho/salesiq-mobilisten-android-sample#22]
Getting below while initializing Zoho MobiListen SDK. Library version used is `2.3.1`

`I/Mobilisten: Android Channel {"error":{"message":"Operation Failed","code":1000}}`

Please help in identifying what is the cause of this error.

**Comment by alokvnair** [comment]
@Angu-G Need urgent support on this

**Comment by Angu-G** [comment]
@alokvnair, Can you please help us with your portal name?

**Comment by Angu-G** [comment]
@alokvnair, It seems your website/embed for which SDK is configured is disabled. Can you please check in your portal side.

**Comment by alokvnair** [comment]
Not having issues now, it got resolved after few hours it seems, no changes were done.
