### ISSUE TITLE
[Question] Is there a way to resume chat after closing chat window?

### ISSUE THREAD

**Issue by dustincatap** [zoho/salesiq-mobilisten-android-sample#26]
I am using the sdk v2.3.2 in a Flutter application, I was calling `ZohoSalesIQ.Visitor.startChat()` in Android to start a chat. I disabled the launcher icon and added my own button to initiate chat.

But when I call the method again (if the user dismisses the previous chat and wants to reopen it), it starts a new chat session.

Here is my code whenever I start/resume chat

```kotlin
  ZohoSalesIQ.Visitor.setName(name)
  ZohoSalesIQ.Visitor.setEmail(email)
  ZohoSalesIQ.Visitor.setContactNumber(contactNumber)
  ZohoSalesIQ.Visitor.startChat(message)
```

Is there a way to restore the previous chat session manually?

**Comment by Angu-G** [comment]
Hello @dustincatap, Please use the following [.show()](https://www.zoho.com/salesiq/help/developer-section/android-sdk-chat-show-v2.0.html) API to open the SDK. You have been using an API to start the new conversation.

**Comment by dustincatap** [comment]
@Angu-G thanks, it works now
