### ISSUE TITLE
FirebaseInstanceId does not work with firebase  com.google.gms:google-services:4.3.8

### ISSUE THREAD

**Issue by hungkoala** [zoho/salesiq-mobilisten-android-sample#29]
got error  when update to com.google.gms:google-services:4.3.8

please update

**Comment by Angu-G** [comment]
Hello @hungkoala, We hope you have mentioned the API used to enable the push notification. As we have already mentioned in our React-Native repo, you can make use of the token that you get from onNewToken() method directly in our API. Will update the same in doc. You can refer to the example code below.

```
@Override
public void onNewToken(String token){
   ZohoSalesIQ.Notification.enablePush(token, --true/false--);
}
```

**Comment by Angu-G** [comment]
@hungkoala We are closing the issue here since it is followed up in another thread.
