### ISSUE TITLE
Is there a way to make inputs mandatory?

### ISSUE THREAD

**Issue by manuls** [zoho/salesiq-mobilisten-android-sample#30]
We would want to make the phone input in the prechat screen mandatory. Is there a way to do this?

**Comment by Angu-G** [comment]
Hi @manuls, Yes it is possible. 
You can find the **Forms** section under _Settings > Brands > "Brand name" > Flow Controls_. You can add the fields from there(Add field option) and opt **Mark this field as mandatory** check box. This will reflect the same in SDK. Attaching a screenshot for reference.
![image](https://user-images.githubusercontent.com/58692424/130579247-69e296aa-947c-4da2-b093-67532270c0c4.png)

**Comment by manuls** [comment]
Oh! I didnt know I had to configure it in the SalesIQ. It is working perfectly. Thanks
