### ISSUE TITLE
Styles not changing

### ISSUE THREAD

**Issue by manuls** [zoho/salesiq-mobilisten-android-sample#31]
With v4.0.1 I am not able to change the colors at all. Did it change the way of changing it and the documentation is not updated?

This simple change is not working
`   
    <style name="Theme.SalesIQ.Base" parent="Theme.SalesIQ.Light.DarkActionBar">
        <item name="siq_launcher_backgroundcolor">@color/myPrimaryColor </item>
        <item name="siq_launcher_unreadbadge_backgroundcolor">@color/red </item>
        <item name="siq_launcher_unreadbadge_textcolor">@color/white</item>
    </style>`

**Comment by Angu-G** [comment]
Hi @manuls, Theme.SalesIQ.Base theme will get applied only when you have opted out of the device sync config [Reference link](https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization.html). 
We have mentioned this in our release notes as well [Release 3.0](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/3.0).

**Comment by manuls** [comment]
My bad @Angu-G. I didnt see the release notes. Thank you for your quick response

**Comment by Angu-G** [comment]
We are glad that the query is clarified. 
You are welcome @manuls!
