### ISSUE TITLE
 AES-512 bit encryption issue for Zoho salesiq 

### ISSUE THREAD

**Issue by dhanashri-patkar** [zoho/salesiq-mobilisten-android-sample#34]
### AES-512 bit encryption
Zoho salesiq is blocking AES-512 bit encryption for Android SDK version 21 and 22. Removing zoho salesiq library works for the encryption code.
<img width="1059" alt="Screenshot 2022-01-27 at 2 18 45 PM" src="https://user-images.githubusercontent.com/72187901/151324332-10c30ebc-65ad-46cf-b939-bd55a2f631ce.png">

**Comment by Angu-G** [comment]
Hello @dhanashri-patkar, Thanks for your patience. Can you please share us any of the error logs/blocking message?

**Comment by Angu-G** [comment]
Hello @dhanashri-patkar, Hope this issue is not related to Mobilisten and note that we are not using any encryption standards in our code. Please get back to us for further queries. Thank you.
