### ISSUE TITLE
Update to Android X

### ISSUE THREAD

**Issue by paolorotolo** [zoho/salesiq-mobilisten-android-sample#37]
Zoho Android library is currently depending on `com.android.support:appcompat-v7:26.1.0` which requires running Jetifier at each build.
Moreover, Google introduced a new Build Analyzer tool in Android Studio, that is flagging your library as AndroidX unsupported.

Please update `com.android.support:appcompat-v7:26.1.0` to AndoirdX to improve build time.

**Comment by DavidBhahirathan** [comment]
Hi @paolorotolo ,

Thanks for writing to us. We have this in our roadmap. We will update you here once this is implemented. 

Regards,
Bhahirathan M

**Comment by DavidBhahirathan** [comment]
Hi @paolorotolo 

Thank you for your patience. We have migrated our SDK from support to AndroidX now. We would recommend you update the latest version [6.0.1](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/v6.0.1) and verify once. Please feel free to write back to us if the issue persists.

Regards,
Bhahirathan M
Zoho SalesIQ.
