### ISSUE TITLE
Duplicate Class Found with GlideToVectorYou Library

### ISSUE THREAD

**Issue by nsuthar20** [zoho/salesiq-mobilisten-android-sample#39]
Duplicate class com.bumptech.glide.GeneratedAppGlideModuleImpl found in modules jetified-GlideToVectorYou-v2.0.0-runtime (com.github.corouteam:GlideToVectorYou:v2.0.0) and jetified-mobilisten-4.3.3-runtime (com.zoho.salesiq:mobilisten:4.3.3)

Duplicate class com.bumptech.glide.GeneratedRequestManagerFactory found in modules jetified-GlideToVectorYou-v2.0.0-runtime (com.github.corouteam:GlideToVectorYou:v2.0.0) and jetified-mobilisten-4.3.3-runtime (com.zoho.salesiq:mobilisten:4.3.3)

**Comment by DavidBhahirathan** [comment]
Hi @nsuthar20 ,

Thanks for writing to us. We're looking into this issue and will update you once we fix it.

As a workaround, please use the same version 'com.github.bumptech.glide:glide:4.13.2' of glide used in Mobilisten to avoid this issue as of now.

For further queries, please write to us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to assist you.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by devang-p-eq** [comment]
facing the same issue in new version
//Zoho version
implementation 'com.zoho.salesiq:mobilisten:4.3.3'

//Glide version
implementation 'com.github.bumptech.glide:glide:4.13.2'
implementation 'com.github.corouteam:GlideToVectorYou:v2.0.0'

**Comment by DavidBhahirathan** [comment]
Hi @nsuthar20 @devang-p-eq ,

This issue has been fixed. Please update to the version [4.4.0](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/v4.4.0) and verify once. Please write back to us if the issue persists.

Regards,
Bhahirathan M,
Zoho SalesIQ.
