### ISSUE TITLE
Dose this library have support Android 13 and 14?

### ISSUE THREAD

**Issue by JackeyPSSPL** [zoho/salesiq-mobilisten-android-sample#40]
- Does this library support Android 13 and 14?

**Comment by DavidBhahirathan** [comment]
Hi @JackeyPSSPL ,

Yes, Mobilisten SDK supports Android 13 and 14.

For further queries, please feel free to write us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to assist you.

Thanks,
Bhahirathan M
Zoho SalesIQ.
