### ISSUE TITLE
How do I open recent Conversations Page on button click?

### ISSUE THREAD

**Issue by bimsina** [zoho/salesiq-mobilisten-android-sample#5]
I would like to open the recent chats if any on custom button click. However if there aren't any recent chats I would like to open a new chat window.

**Comment by Angu-G** [comment]
Hello @bimsina , You can do the same using [.open()](https://www.zoho.com/salesiq/help/developer-section/android-sdk-chat-open.html) API we provided.

**Comment by bimsina** [comment]
As the documentation says _If the chatID is not mentioned, a recent chat or a new chat(if no chats are available) will be opened._ , but I don't want to open the recent chat I want to open a list of recent chats that the user has performed.

**Comment by bimsina** [comment]
Right now (I think) the only way to open the recent conversations is by enabling the launcher button , but I need to disable the launcher button and add a custom button to open the recent conversations page.
![Uploading Screenshot_20200617-121701.png…]()

**Comment by Angu-G** [comment]
We are working on this and will update here in a couple of weeks.

**Comment by bimsina** [comment]
@Angu-G Is there an ETA on when this will be available?

**Comment by Angu-G** [comment]
@bimsina It will be available by next week.

**Comment by Angu-G** [comment]
@bimsina , you can open the conversation UI of SDK using **ZohoSalesIQ.Chat.show()** API. It is available from [2.1 version](https://github.com/zoho/salesiq-mobilisten-android-sample/releases/tag/2.1).

**Comment by bimsina** [comment]
Seems like I can't access the method.
It gives me an error
`Unresolved reference: Chat`
![unresolved ref](https://user-images.githubusercontent.com/29589003/86534002-e61a4380-bef4-11ea-8445-8c6ac91b4312.png)

**Comment by Angu-G** [comment]
@bimsina, If you are working on the Kotlin project, Please use **ZohoLiveChat** instead of ZohoSalesIQ. `ZohoLiveChat.Chat.show()`
