### ISSUE TITLE
Cannot change strings in "Start chat" screen

### ISSUE THREAD

**Issue by manuls** [zoho/salesiq-mobilisten-android-sample#7]
The only strings that can be changed are the ones in the documentation: https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization-strings.html but it would be nice to be able to change all texts

**Comment by Angu-G** [comment]
@manuls , We are working on this and it will be available in a couple of weeks.

**Comment by Angu-G** [comment]
@manuls, this is live already. Please use the latest version(2.3.1) for customizing the strings. [Help Doc link](https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization-strings.html)
